# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb/ocr.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pb/ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpb/ocr.proto\x12\x08ocr_grpc\" \n\rDetectRequest\x12\x0f\n\x07\x62\x36\x34_img\x18\x01 \x01(\t\"\"\n\x0e\x44\x65tectResponse\x12\x10\n\x08response\x18\x01 \x03(\t2D\n\x03OCR\x12=\n\x06\x44\x65tect\x12\x17.ocr_grpc.DetectRequest\x1a\x18.ocr_grpc.DetectResponse\"\x00\x42\x08Z\x06pb/ocrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006pb/ocr'
  _globals['_DETECTREQUEST']._serialized_start=26
  _globals['_DETECTREQUEST']._serialized_end=58
  _globals['_DETECTRESPONSE']._serialized_start=60
  _globals['_DETECTRESPONSE']._serialized_end=94
  _globals['_OCR']._serialized_start=96
  _globals['_OCR']._serialized_end=164
# @@protoc_insertion_point(module_scope)
