// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: ocr.proto

package ocr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OCR_Detect_FullMethodName = "/ocr_grpc.OCR/Detect"
)

// OCRClient is the client API for OCR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OCRClient interface {
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
}

type oCRClient struct {
	cc grpc.ClientConnInterface
}

func NewOCRClient(cc grpc.ClientConnInterface) OCRClient {
	return &oCRClient{cc}
}

func (c *oCRClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, OCR_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OCRServer is the server API for OCR service.
// All implementations must embed UnimplementedOCRServer
// for forward compatibility.
type OCRServer interface {
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	mustEmbedUnimplementedOCRServer()
}

// UnimplementedOCRServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOCRServer struct{}

func (UnimplementedOCRServer) Detect(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedOCRServer) mustEmbedUnimplementedOCRServer() {}
func (UnimplementedOCRServer) testEmbeddedByValue()             {}

// UnsafeOCRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OCRServer will
// result in compilation errors.
type UnsafeOCRServer interface {
	mustEmbedUnimplementedOCRServer()
}

func RegisterOCRServer(s grpc.ServiceRegistrar, srv OCRServer) {
	// If the following call pancis, it indicates UnimplementedOCRServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OCR_ServiceDesc, srv)
}

func _OCR_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCRServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCR_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCRServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OCR_ServiceDesc is the grpc.ServiceDesc for OCR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OCR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocr_grpc.OCR",
	HandlerType: (*OCRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _OCR_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocr.proto",
}
